name: Freetz Build

on:
# Löst den Workflow bei jedem Push auf den 'main'-Branch aus
push:
branches:
- main
# Ermöglicht auch das manuelle Starten über die GitHub-Oberfläche
workflow_dispatch:

jobs:
build:
runs-on: ubuntu-latest # Nutzt den kostenlosen Linux-Runner
steps:
- name: Checkout Code
uses: actions/checkout@v4
with:
# Freetz benötigt oft Submodule
submodules: true

- name: Build Freetz Image
run: |
# Notwendige Build-Werkzeuge installieren
sudo apt-get update
sudo apt-get install -y build-essential subversion git

# Freetz-Quellen (Trunk) herunterladen
svn co https://svn.freetz.org/trunk freetz-trunk
cd freetz-trunk

# Ihre hochgeladene .config-Datei verwenden
cp ../.config .

# Build-Prozess starten (V=0 reduziert die Ausgabe)
make V=0

- name: Upload Freetz Image
uses: actions/upload-artifact@v4
with:
name: freetz-image-download
# Das fertige Image liegt unter freetz-trunk/images/
path: freetz-trunk/images/*.image
# Bild wird 7 Tage gespeichert
retention-days: 7
